title: Xingchi Wu's Homepage
page-top-title: Xingchi Wu
top-section-bg-text: Sustainable Pavement Materials
home-subtitle: Xingchi Wu;吴兴驰
copyright-text: '&copy; Xingchi Wu 2023-2025. All Rights Reserved.'
